### ISSUE TITLE
Where are you? (just wondering)

### ISSUE THREAD

**Issue by Nick-77ab2** [wildex999/ICBM#4]
it seems like yo just disappeared after September.

**Comment by wildex999** [comment]
Sorry, got a busy with School, and with 1.6 becoming less relevant, I didn't really have the motivation to continue this project.
I did start work on my own 1.7 mod with some ideas, might continue that at some point.
But this project, at least my involvement, is done.

**Comment by shadoxxhd** [comment]
could you pls at least look into the issue i submitted some seconds ago? doesnt seem to be much work for someone who knows what he does, maybe its just one broken line...

**Comment by wildex999** [comment]
I'll take a look at it
