### ISSUE TITLE
/sentry command

### ISSUE THREAD

**Issue by shadoxxhd** [wildex999/ICBM#7]
its not really an issue, but a question: how the hell does the /sentry command work? it always tells me "you need to select a sentry", and i have no clue how to do so (i tried everything i could imagine).
i hope you can help me with this, thanks in advance

**Comment by wildex999** [comment]
Sorry, don't know much about the sentries =/ And I'm pretty much no longer maintaining this version anymore =/ The original developers have moved on to 1.7, jump over there and look at that ;)

**Comment by Nick-77ab2** [comment]
could you leave the link to the original developers just in case people dont know?
